### ISSUE TITLE
Boot loop when flashing via PixelExperience Recovery

### ISSUE THREAD

**Issue by panda4k** [Spectrum-Kernel/kernel_xiaomi_sm6250#1]
Flashing the kernel via PixelExperience Recovery over the PixelExperience+ ROM on Miatoll causes a boot loop.

I've opened a new Issue on their Github but was recommended to do it by the Kernel Github [here](https://github.com/PixelExperience/android-issues/issues/2584).

**Comment by Edgars-Cirulis** [comment]
Official PE/LOS uses pixel thermal stuff, and spectrum kernel dosn't have the dependency. I see there is only two kernel that support their Thermal stuff. Sorry but I will not make support for LOS/PE Official. 

Regarding Spectrum Team.
